services:
  - type: web
    name: whatsapp-x
    runtime: docker
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_STORAGE_TYPE
        value: mongo
      - key: PORT
        value: 12005
    
    # Disk commented out - Enable if using LocalAuth on a paid plan
    # disk:
    #   name: xbot_session
    #   mountPath: /app/session
    #   sizeGB: 1

    healthCheckPath: /health
    autoDeploy: true
